config/routes.rb
Rails.application.routes.draw do
  # resources :posts

  root "home#index"
  get "/" => "home#index"
  get "/about" => "home#about"

  resources :users, only: [:new, :create]

  resources :blogs, only: [:index, :show] do
    resources :comments
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  # resources :codes do
  #   resources :snippets, only: [:show, :destroy]
  # end

  # get "/blogs" => "home#blogs"
  # get "/blogs/:id" => "home#view", as: :view_blog

  #POST ROUTES
  resources :posts
  # get "/posts" => "posts#index"
  # post "/posts" => "posts#create"
  # get "/posts/new" => "posts#new", as: :new_post
  # get "/posts/:id/edit" => "posts#edit", as: :edit_post
  # get "/posts/:id" => "posts#show", as: :post
  # patch "/posts/:id" => "posts#update"
  # delete "/posts/:id" => "posts#destroy"

  #COMMENT ROUTES
  resources :comments, only: [:index, :create]
  # get "/comments" => "comments#index"
  # post "/comments" => "comments#create"

  #SEARCH ROUTES
  # resources :search
  get "/search" => "search#index"
  # get "/search/:id" => "search#result", as: :search
  post "/search" => "search#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end

    # we define an ability in here that states that only the user who created
    # a question is able to manage the question.
    # :manage here includes any operation such as: destroy, edit, delete, approve etc
    # can :manage, Question do |q|
    #   user == q.user
    # end
    #
    # can :manage, Answer do |a|
    #   user == a.user
    # end
    #
    # can :destroy, Answer do |a|
    #   user == a.question.user
    # end



    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  #category: title(required)
  validates(:title, {presence: true})
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates(:body, {presence: true})
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  #contact: email, name, subject and message
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  # post: title(required & unique), body
  validates(:title, {presence: true,
                    uniqueness: true})
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_secure_password

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: VALID_EMAIL_REGEX


  after_initialize :set_default_values

  def set_default_values
    self.admin ||= 0
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    # @blog = Post.all.order("created_at DESC")

    # pagination
    @page = 1
    @page = params[:page] if params.has_key?(:page)
    @blog = Post.paginate(:page => @page, :per_page => 5).order("created_at DESC")
    # @blog = Post.all
  end
  def show
    @blog = Post.find(params[:id])
    # @comment_count = params[:id]
    # @comment_count = Comment.where(post_id: params[:id]).count
    # @comment = Comment.all.order("created_at DESC")
    # @comment = Comment.where(post_id: params[:id]).order("created_at DESC")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :authenticate_user
  def create
    comment_params = params.permit([:body, :post_id])
    # comment_params = params.require(:comment).permit([:body, :postid])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    # render text: "inside add comment #{params} <br>id: #{params[:postid]}"
    # render text: "#{comment_params} redirect: #{view_blog_path(params[:postid])}"
    if @comment.save
        redirect_to(blog_path(params[:post_id]))
    else
        render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :control_panel
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def find_post
    @post = Post.find params[:id]
  end

  def control_panel
    authenticate_user
    if @current_user
      unless @current_user.admin
        redirect_to blogs_path, notice: "Please login with Admin privileges!"
      end
    end
  end


  def index
    @post = Post.all.order("created_at DESC")
    #   @post = Post.all.order("created_at DESC")
    # else
    #   redirect_to blogs_path
    # end
    # render text: @current_user.inspect
    # render text: authenticate_user.inspect
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
        redirect_to(posts_path)
    else
        render :new
    end
  end
  def show
    # @post = Post.find(params[:id])
  end
  def edit
    # @post = Post.find(params[:id])
  end
  def update
    # render text: "inside update #{params}"
    # @post = Post.find params[:id]
    if @post.update(post_params)
      # render text: "path: #{posts_path}"
      redirect_to posts_path
    else
      render :edit
    end
  end
  def destroy
    # @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

  def post_params
    post_params = params.require(:post).permit([:title, :body])
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    search_params = params.permit([:search])
    @search = search_params[:search]
    @page = 1
    @page = params[:page] if params.has_key?(:page)
    @blog = Post.where(["title ilike ? OR body ilike ?", "%#{@search}%", "%#{@search}%"]).order("created_at DESC")
    # render text: "search: #{@search} <br>path: #{request.env['PATH_INFO']}"


    # @page = 1
    # @page = params[:page] if params.has_key?(:page)
    # @blog = Post.paginate(:page => @page, :per_page => 5).order("created_at DESC")
    # search
    # if params.has_key?(:search)
    #   @search = params[:seach]
    #   @blog = Post.paginate(:page => @page, :per_page => 5).where(["title ilike ? OR body ilike ?", "%#{@search}%", "%#{@search}%"]).order("created_at DESC")
    # else
    #   @blog = Post.paginate(:page => @page, :per_page => 5).order("created_at DESC")
    # end
    # Post.where(["title ilike ? OR body ilike ?", '%umbria%', '%umbria%'])
    # Post.where(title ILIKE "%Second%")  # search field in db case-insensitive only postgresql
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email,
                  :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to blogs_path, notice: "account created!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_login.html.erb
<!--==================== Modal =============================================-->
<div class="modal fade" id="loginModal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content col-md-7 col-md-offset-3">
        <div class="modal-body">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title text-center">Sign in</h2>
          <div class="signup-tagline text-center">and comments your blogs</div>
            <img class="profile-img" src="https://scontent.cdninstagram.com/hphotos-xta1/t51.2885-15/s320x320/e35/11378916_1047515518625819_492552296_n.jpg"
                alt="">
                <%= form_tag sessions_path, :class => "form-signin" do %>
                  <%= email_field_tag :email, "", class: "form-control", placeholder: "Email", required:true %>
                  <%= password_field_tag :password, "", class: "form-control", placeholder: "Password", required:true %>
                  <%= submit_tag "Sign In", class: "btn btn-lg btn-primary btn-block" %>
                <% end %>
        </div>
        <%= link_to "Not member? Sign up here", new_user_path, class:"text-center new-account" %>
    </div>


  </div>
</div>
<script>
$(document).ready(function(){
    $("#submitBtn").click(function(){
        $("#loginModal").modal();
    });
});
</script>

app/views/blogs/index.html.erb
  <!-- <div class="blog-border"> -->
  <div class="">
    <h1 class="lobster text-center">the sound of life</h1>
    <div class="site-head-line text-center"></div>
    <% @blog.each do |p| %>
    <%#= p.user.inspect %>
      <div><%= link_to p.title, blog_path(p), class: "blog-title-list" %></div>
      <div class="date-red-sm margin-bottom-10">
        <%= p.created_at.strftime("%B %d, %Y at %I:%M %P") %>
      </div>
      <!-- <%# if @blog.user %>
      <div class="created_by">
          Created by:
          <%#= @blog.user.first_name %> <%#= @blog.user.last_name %>
      </div>
      <%# end %> -->
      <div class="blog-content">
        <%= p.body.split.first(50).join(' ') %>
        <%#= simple_format(p.body, {}, :sanitize => false).split.first(50).join(' ') %> ..
      </div>
      <hr>
    <% end %>
    <!-- <div class="text-center"><%#= will_paginate @blog %></div> -->
    <% if @blog.total_pages > 1 %>
    <div>
      <ul class="pager">
        <% path = request.env['PATH_INFO'] %>
        <% if @page.to_i > 2 %>
          <li><%= link_to "Previous", "#{path}?page=#{@page.to_i - 1}" %></li>
        <% else %>
          <li><%= link_to "Previous", path %></li>
        <% end %>
        <% if @page.to_i < @blog.total_pages %>
          <li><%= link_to "Next", "#{path}?page=#{@page.to_i + 1}" %></li>
        <% else %>
          <li><%= link_to "Next", "#{path}?page=#{@blog.total_pages}" %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <!-- current path: <%#= request.env['PATH_INFO'] %>
    <br>
    current page: <%#= @page %>
    <br>
    last page: <%#= @blog.total_pages %> -->
  </div>

app/views/blogs/show.html.erb
<%#= @blog.comments.inspect %>
<%#= @post.inspect %>
<h1 class="lobster text-center"><%= @blog.title %></h1>
<br>
<div class="blog-border">
  <div class="blog-content margin-top-30">
    <blockquote>
      <%= @blog.created_at.strftime("%B %d, %Y at %I:%M %P") %>
    </blockquote>
    <%= simple_format(@blog.body, {}, :sanitize => false) %>
  </div>

  <div>

  </div>

  <div class="panel panel-default">
    <div class="panel-body">
        <%= form_tag comments_path do %>
          <div class="form-group">
            <%= text_area_tag(:body, "", rows: "4", class: "form-control", placeholder: "Enter your comment ...", ) %>
            <%= hidden_field_tag(:post_id, @blog.id) %>
          </div>
          <div class="form-group">
            <% if session[:user_id] %>
              <%= submit_tag("Submit comment", class: "btn btn-primary btn-sm") %>
            <% else %>
              <button type="button" class="btn btn-primary btn-sm" id="submitBtn">Submit Comment</button>
            <% end %>
          </div>
        <% end %>

    </div>
  </div>

  <div class="title font-24">
    <%= @blog.comments.count %> Comments:
  </div>
  <% @blog.comments.each do |p| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <div><span class="glyphicon glyphicon-user"> </span> <%= p.user.first_name %> <%= p.user.last_name %></div>
        <div><span class="glyphicon glyphicon-time"> </span> <%= p.created_at.strftime("%B %d, %Y at %I:%M %P") %></div>
        <p><%= p.body %></p>
      </div>
    </div>
  <% end %>
</div>
<%= render "login" %>

app/views/home/about.html.erb
  <div>
    <h1 class="lobster text-center">about me</h1>
    <p><img style="height:200px; float: left; padding:0 20px 10px 0" src="http://irinavalentino.com/wp-content/uploads/2014/01/Smile.jpg">
      Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
      <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
  </div>

app/views/home/index.html.erb
<!-- <div class="body container-fluid">
  <div class="row" id="box-search">
      <div class="thumbnail text-center col-md-12 col-lg-12 col-sm-12">
          <img src="http://andnorth.com/wp-content/uploads/2015/04/keenguide_wb_6.jpg" alt="" class="img-responsive">
          <div class="caption">
              <h1 class="">THE SOUND OF LIFE</h1>
          </div>
      </div>
  </div>
</div> -->

            <!-- <div class="ratio" style="background-image:url('http://andnorth.com/wp-content/uploads/2015/04/keenguide_wb_6.jpg')" /> -->
            <div class="ratio" style="background-image:url('http://4.bp.blogspot.com/-Z9r-RBHSms8/VhEQ2tbTysI/AAAAAAAAAck/NgYkenDHyLQ/s1600/photo-1423753623104-718aaace6772.jpg')" />
            <div class="caption text-center">
                <h1 class="heading lobster text-lowercase">THE SOUND OF LIFE</h1>
            </div>

app/views/search/index.html.erb
<h1 class="lobster text-center">the sound of life</h1>
<div class="site-head-line text-center"></div>
<h4>Search titles or contents for : <%= @search %></h4>
<br>
  <% if @blog.count > 0 then %>
    <% @blog.each do |p| %>
      <div><%= link_to p.title, blog_path(p), class: "blog-title-list" %></div>
      <div class="date-red-sm margin-bottom-10">
        <%= p.created_at.strftime("%B %d, %Y at %I:%M %P") %>
      </div>
      <div class="blog-content">
        <%= p.body.split.first(50).join(' ') %>
        <%#= simple_format(p.body, {}, :sanitize => false).split.first(50).join(' ') %> ..
      </div>
      <hr>
    <% end %>
  <% else %>
    <div>
      No result found
    </div>
  <% end %>