config/routes.rb
Rails.application.routes.draw do
  # resources :posts

  root "home#index"
  get "/" => "home#index"
  get "/about" => "home#about"

  resources :users, only: [:new, :create]

  resources :blogs, only: [:index, :show] do
    resources :comments
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  # resources :codes do
  #   resources :snippets, only: [:show, :destroy]
  # end

  # get "/blogs" => "home#blogs"
  # get "/blogs/:id" => "home#view", as: :view_blog

  #POST ROUTES
  resources :posts
  # get "/posts" => "posts#index"
  # post "/posts" => "posts#create"
  # get "/posts/new" => "posts#new", as: :new_post
  # get "/posts/:id/edit" => "posts#edit", as: :edit_post
  # get "/posts/:id" => "posts#show", as: :post
  # patch "/posts/:id" => "posts#update"
  # delete "/posts/:id" => "posts#destroy"

  #COMMENT ROUTES
  resources :comments, only: [:index, :create]
  # get "/comments" => "comments#index"
  # post "/comments" => "comments#create"

  #SEARCH ROUTES
  # resources :search
  get "/search" => "search#index"
  # get "/search/:id" => "search#result", as: :search
  post "/search" => "search#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end

    # we define an ability in here that states that only the user who created
    # a question is able to manage the question.
    # :manage here includes any operation such as: destroy, edit, delete, approve etc
    # can :manage, Question do |q|
    #   user == q.user
    # end
    #
    # can :manage, Answer do |a|
    #   user == a.user
    # end
    #
    # can :destroy, Answer do |a|
    #   user == a.question.user
    # end



    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  #category: title(required)
  validates(:title, {presence: true})
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates(:body, {presence: true})
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  #contact: email, name, subject and message
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  # post: title(required & unique), body
  validates(:title, {presence: true,
                    uniqueness: true})
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_secure_password

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: VALID_EMAIL_REGEX


  after_initialize :set_default_values

  def set_default_values
    self.admin ||= 0
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    # @blog = Post.all.order("created_at DESC")

    # pagination
    @page = 1
    @page = params[:page] if params.has_key?(:page)
    @blog = Post.paginate(:page => @page, :per_page => 5).order("created_at DESC")
    # @blog = Post.all
  end
  def show
    @blog = Post.find(params[:id])
    # @comment_count = params[:id]
    # @comment_count = Comment.where(post_id: params[:id]).count
    # @comment = Comment.all.order("created_at DESC")
    # @comment = Comment.where(post_id: params[:id]).order("created_at DESC")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :authenticate_user
  def create
    comment_params = params.permit([:body, :post_id])
    # comment_params = params.require(:comment).permit([:body, :postid])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    # render text: "inside add comment #{params} <br>id: #{params[:postid]}"
    # render text: "#{comment_params} redirect: #{view_blog_path(params[:postid])}"
    if @comment.save
        redirect_to(blog_path(params[:post_id]))
    else
        render :new
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :control_panel
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def find_post
    @post = Post.find params[:id]
  end

  def control_panel
    authenticate_user
    if @current_user
      unless @current_user.admin
        redirect_to blogs_path, notice: "Please login with Admin privileges!"
      end
    end
  end


  def index
    @post = Post.all.order("created_at DESC")
    #   @post = Post.all.order("created_at DESC")
    # else
    #   redirect_to blogs_path
    # end
    # render text: @current_user.inspect
    # render text: authenticate_user.inspect
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
        redirect_to(posts_path)
    else
        render :new
    end
  end
  def show
    # @post = Post.find(params[:id])
  end
  def edit
    # @post = Post.find(params[:id])
  end
  def update
    # render text: "inside update #{params}"
    # @post = Post.find params[:id]
    if @post.update(post_params)
      # render text: "path: #{posts_path}"
      redirect_to posts_path
    else
      render :edit
    end
  end
  def destroy
    # @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

  def post_params
    post_params = params.require(:post).permit([:title, :body])
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    search_params = params.permit([:search])
    @search = search_params[:search]
    @page = 1
    @page = params[:page] if params.has_key?(:page)
    @blog = Post.where(["title ilike ? OR body ilike ?", "%#{@search}%", "%#{@search}%"]).order("created_at DESC")
    # render text: "search: #{@search} <br>path: #{request.env['PATH_INFO']}"


    # @page = 1
    # @page = params[:page] if params.has_key?(:page)
    # @blog = Post.paginate(:page => @page, :per_page => 5).order("created_at DESC")
    # search
    # if params.has_key?(:search)
    #   @search = params[:seach]
    #   @blog = Post.paginate(:page => @page, :per_page => 5).where(["title ilike ? OR body ilike ?", "%#{@search}%", "%#{@search}%"]).order("created_at DESC")
    # else
    #   @blog = Post.paginate(:page => @page, :per_page => 5).order("created_at DESC")
    # end
    # Post.where(["title ilike ? OR body ilike ?", '%umbria%', '%umbria%'])
    # Post.where(title ILIKE "%Second%")  # search field in db case-insensitive only postgresql
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email,
                  :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to blogs_path, notice: "account created!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<div class="well">

  <%= @post.errors.full_messages.join(", ") %>
  <%#= form_for @post, :html => {:class => "form-horizontal"} do |f| %>
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title, class: "control-label text-right" %>
      <%= f.text_field :title, class: "form-control", placeholder: "blog title" %>
    </div>
    <div class="form-group">
      <%= f.label :body, class: "control-label text-right"  %>
      <%= f.text_area :body, class: "form-control", placeholder: "blog contents", rows: "12"%>
    </div>
    <div class="form-group">
        <%= f.submit(class: "btn btn-primary") %>
        <%= link_to 'Cancel', posts_path, class:"btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/posts/edit.html.erb
<h3 class="blog-sub-title text-center">edit a post</h3>

<%= render "form" %>

app/views/posts/index.html.erb
<div>
  <!-- <div class="site-head-line text-center margin-top-30"></div> -->
  <div class="margin-top-30">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Title</th>
          <th>Category</th>
          <th>Date created</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% num = 0 %>
        <% @post.each do |p| %>
        <% num += 1 %>
        <tr><td><%= num %></td>
            <td><%= link_to p.title, post_path(p) %></td>
            <td>uncategorized</td>
            <td><%= p.created_at.strftime("%b %d, %Y") %></td>
            <td><%= link_to "", edit_post_path(p), class: "glyphicon glyphicon-edit" %>
                <%= link_to "", post_path(p), class: "glyphicon glyphicon-trash",
                            method: :delete,
                            data: {confirm: "Are you sure?"} %>
            </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<%#= @current_user.admin.inspect %>
</div>

app/views/posts/new.html.erb
<h3 class="blog-sub-title text-center">create a new post</h3>
  <%= render "form" %>

app/views/posts/posts.html.erb
<p>Create a new post<%#= link_to 'Add new Post', new_post_path %></p>
<h1>ADMIN POSTS</h1>
<%# @post.each do |p| %>
  <%#= link_to p.title, posts_path(p) %>
  <hr>
<%# end %>

app/views/posts/show.html.erb
<!-- <h2><%#= @post.inspect %></h2> -->
<div class="well margin-top-30">
  <h1 class="lobster text-center"><%= @post.title %></h1>
  <p class="text-center">
    <%= link_to "Back", posts_path %> |
    <%= link_to "Edit", edit_post_path(@post) %> |
    <%= link_to "Delete", post_path(@post),
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
  </p>
  <div class="blog-content margin-top-30">
    <blockquote>
      <%= @post.created_at.strftime("%B %d, %Y") %>
    </blockquote>
    <%= simple_format(@post.body, {}, :sanitize => false) %>
  </div>

</div>

app/views/users/new.html.erb
  <div class="col-md-7 col-md-offset-3">
      <div class="account-wall">
        <h2 class="modal-title text-center">Sign up</h2>
        <div class="signup-tagline text-center">Sign up to follow your favorite blogs</div>
          <%= @user.errors.full_messages.join(", ") %>
          <img class="profile-img" src="https://scontent.cdninstagram.com/hphotos-xta1/t51.2885-15/s320x320/e35/11378916_1047515518625819_492552296_n.jpg"
              alt="">
          <%= form_for @user, :html => {:class => "form-signin"} do |f| %>
            <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", required:true, id: "first_name" %>
            <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name", required:true %>
            <%= f.email_field :email, class: "form-control", placeholder: "Email", required:true %>
            <%= f.password_field :password, class: "form-control", placeholder: "Password", required:true %>
            <%= f.submit "Sign Up", class: "btn btn-lg btn-primary btn-block" %>
        <% end %>
      </div>
      <%= link_to "Already sign up? Login here", new_session_path, class:"text-center new-account" %>
  </div>